### ISSUE TITLE
SonaQube template

### ISSUE THREAD

**Issue by egevorkyan** [gatblau/artisan#22]
I found issue when using SonarQube_OpenshiftCatalogTemplate.yaml to spin up sonarqube. POD is coming up but:

1. service is mapped to 8080:8080, but container itself is listening Port 9000.
   my service name is sonarqube   ServiceIP: 172.30.154.168:8080. To test if POD is responding on 8080, simplest way is to curl from another POD to 172.30.154.168:8080 .
Result: 
sh-4.4$ curl 172.30.154.168:8080
curl: (7) Failed to connect to 172.30.154.168 port 8080: Connection refused

Changing Service port to 9000
my service name is sonarqube   ServiceIP: 172.30.154.168:9000
Result:
sh-4.4$ curl 172.30.154.168:9000
<!doctype html><html lang="en">

------------------------------------------------------------------------

2. Issue is that sonarqube not responding on https url
https url result: Application is not available

http url result: Log In to SonarQube

**Comment by gatblau** [comment]
Sonar port has been updated in pull request #24
